### ISSUE TITLE
The main content plays for a short time after post-roll

### ISSUE THREAD

**Issue by askaliuk** [videojs/videojs-contrib-ads#357] opened 2018-03-26 22:29 UTC
### Description

Main content plays for a short time after post-roll 

### Steps to Reproduce

* Visit http://bit.ly/2GtisP0
* Watch pre-roll 
* Seek the video to the end to see post-roll
* Watch post-roll
* Notice that the main video plays for a couple of seconds from the start again before post-roll

#### Expected Results

No main content playback after post-roll

#### Actual Results

The main content plays for a short after post-roll

### Versions

**videojs-contrib-ads version**: 6.0.0
**Video-js version**: 6.6.3
**Other plugins**:  standard integration example from videojs-contrib-ads repo

### Platforms

**Browsers**: Chrome, FF, Safari latest

**OS/Devices**: OSX 10.12, Android 7

**Comment by incompl** [comment] 2018-03-27 15:39
Thank you for the comprehensive bug report! I reproduced this issue in 6.0.0 and confirmed the issue is resolved in master, most likely as a result of https://github.com/videojs/videojs-contrib-ads/commit/81699b4635c43fc711906b12cae8deccb79ad270. I'll do a patch release to get you the fix.

**Comment by incompl** [comment] 2018-03-27 16:10
I've released videojs-contrib-ads 6.0.1, could you verify if that resolves this issue?

**Comment by askaliuk** [comment] 2018-03-27 18:18
@incompl thank you very much for quick response!
I confirm that the issue is fixed in 6.0.1

**Closed** 2018-03-27 18:18 UTC
