### ISSUE TITLE
player ads not a function 

### ISSUE THREAD

**Issue by deysuman** [videojs/videojs-contrib-ads#314] opened 2018-01-02 18:02 UTC
Here is full code 
```
import React from 'react';
import videojs from 'video.js';
import ads from  'videojs-contrib-ads/dist/videojs.ads.min.js';




export default class MediaPlayer extends React.Component {

   constructor(props){
    super(props);
    this.togglePlayback = this.togglePlayback.bind(this);
   }

  componentDidMount() {

    videojs.registerPlugin('examplePlugin', function() {
        this.ads();
    });


  
    this.player = videojs(this.videoNode, this.props, function onPlayerReady() {

      

       this.examplePlugin();


    });


   
  }


  componentWillUnmount() {
    if (this.player) {
      this.player.dispose()
    }
  }


  pausevideo(){
    this.player.pause();
  }




  togglePlayback() {
    //alert("Hi");
    if(!this.player.paused){
        this.pausevideo();
    }
  }
  render() {
    return (
      <div data-vjs-player> 
          <button onClick={this.togglePlayback} className="videostopbutton"></button>
        <video ref={ node => this.videoNode = node } className="video-js"></video>
      </div>
    )
  }
}
```
![bb](https://user-images.githubusercontent.com/22560930/34494066-a830f0a2-f014-11e7-8e88-48e7b48408fc.png)

Show this

**Comment by incompl** [comment] 2018-01-24 23:21
In the import you're importing from the dist files, and our dist files expect video.js to be available globally. Instead, you should import the package like this: `import "videojs-contrib-ads"`. However, we also have an issue where if you're using vjs6 contrib-ads will still get its own version of vjs and thus it won't be registered. We have a proposed fix in this PR: https://github.com/videojs/videojs-contrib-ads/pull/321

**Comment by incompl** [comment] 2018-02-28 22:17
Is this still an issue? We are also adding a working example of how to import the project if that helps: https://github.com/videojs/videojs-contrib-ads/pull/312/files#diff-80b85f7007dced052a8e8ddb693843cb

**Comment by incompl** [comment] 2018-02-28 22:46
Closing this as a duplicate of #326 but please let us know if we can help!

**Closed by incompl** 2018-02-28 22:46 UTC
Labels: bug
