### ISSUE TITLE
Videojs events still propagated when the minified version of Videojs is used

### ISSUE THREAD

**Issue by gabrieli** [videojs/videojs-contrib-ads#126] opened 2015-10-27 11:14 UTC
Based on the event propagation changes you've made starting with 2.0.0, I understand that it's expected for usual player evens to not be propagated during ad play. For example, on an ad end, the plugin would send only the 'adended' event.

When using the cdn version of videojs - http://vjs.zencdn.net/4.12.14/video.js - I see that on ad end, both 'adended' and 'ended' events are sent. 
Weirdly enough, when using the dev version of Videojs, built locally, the player behaves as expected and only sends 'adended' on ad end.

**Comment by spra85** [comment] 2015-10-28 14:30
Following up on @gabrieli's comment.  I thought the intent of the changes in 2.0.0 to prefix `content` and `ad` on the native HTML5 video events was to allow plugins that care about whether it is an ad or content -- but also preserve the native non-prefixed HTML5 events.

Hoping this thread can provide clarity on which is the expected behavior based on the changes released in 2.0.0 to redispatch the video events.  It's definitely an issue that was initially hard to track down that the minified version of `video.js` has different behavior with this `redispatch` functionality than the dev version

**Comment by spra85** [comment] 2015-10-29 12:12
Believe it's related to the logic in this block:

https://github.com/videojs/videojs-contrib-ads/blob/be6a756489f2180f23b31130d5f63df57c3fb04e/src/videojs.ads.js#L396

In a commit (https://github.com/videojs/videojs-contrib-ads/commit/08d7f2dd5952d7ed43e9939cd9f231d2b00cbdbb) by @gkatsev

**Comment by gabrieli** [comment] 2015-10-29 12:55
Set up two quick demo pages for you: 
Ended event not being sent when ads are playing - http://demo.videoplaza.com/vp-gabriel/brightcove/diff/dev.html

Ended even sent (behaviour seen when using the minified, cdn version) - http://demo.videoplaza.com/vp-gabriel/brightcove/diff/prod.html

**Comment by gkatsev** [comment] 2015-10-29 15:47
I think this might be the designed behavior. What you want to make sure is that you load this plugin first before all your other plugins because otherwise you'll see the two events.

**Comment by spra85** [comment] 2015-10-29 16:02
@gkatsev - The main problem is that there is different behavior with this plugin if you're using the minified version of video.js then if you're using the dev version of video.js, e.g. this plugin does not work consistently with both versions.

**Comment by incompl** [comment] 2016-11-14 22:06
The demo pages in the previous comment are no longer available. If this issues exists I would like to resolve it, so if anyone is still seeing it please reopen and include an example configuration so we can reproduce it. Thanks!

**Closed by incompl** 2016-11-14 22:06 UTC
